# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneCollection',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SampleIngestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('input_file', models.CharField(max_length=1000)),
                ('gene_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coveragedbingestion.GeneCollection')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult')),
                ('seconds', models.IntegerField(default=None, null=True))
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sampleingestion',
            unique_together=set([('name', 'gene_collection')]),
        ),
    ]
