# Generated by Django 2.0.2 on 2018-04-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coveragedbingestion', '0002_sampleingestion_name_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='coveragedbingestion.GeneCollection')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDefinition',
            fields=[
                ('property_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('string', 'string'), ('float', 'float'), ('integer', 'integer')], max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='collectionproperty',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='coveragedbingestion.PropertyDefinition'),
        ),
    ]
