# Generated by Django 2.0.2 on 2018-04-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coveragedbingestion', '0003_auto_20180428_2017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionproperty',
            unique_together={('property_type', 'collection')},
        ),
    ]
